include:
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - test
  - deploy

check-rules:
  stage: test
  variables:
    DOCKER_IMAGE: docker:stable
    DIND_IMAGE: docker:dind
  image: ${DOCKER_IMAGE}
  services:
    - ${DIND_IMAGE}
  script:
    - ./check-rules.sh

.deploy:
  variables:
    STACK: metric
    STATUS_CHECK_DELAY: 200
  environment:
    url: https://${CI_PROJECT_NAME}.${DD_TRAEFIK_DOMAIN}
