include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - test
  - deploy

variables:
  STACK: metric
  STATUS_CHECK_DELAY: 200
  IMAGE_NAME: prom/prometheus
  IMAGE_TAG: v2.8.0

check-rules:
  stage: test
  image: docker:stable
  script:
    - ./check-rules.sh

.deploy:
  script:
    - >
      deploy.sh IMAGE_NAME=${IMAGE_NAME} IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} UI_AUTH=${UI_AUTH}
      PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME} JOBS=${JOBS} STORAGE_TSDB_RETENTION_TIME=${STORAGE_TSDB_RETENTION_TIME}
      STORAGE_TSDB_RETENTION_SIZE=${STORAGE_TSDB_RETENTION_SIZE}
  environment:
    url: https://${CI_PROJECT_NAME}.${PUBLIC_HOSTNAME}
