global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dockerd-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.dockerd-exporter'
      type: 'A'
      port: 9323

  - job_name: 'kafka'
    dns_sd_configs:
    - names:
      - 'tasks.kf-1'
      - 'tasks.kf-2'
      - 'tasks.kf-3'
      type: 'A'
      port: 9998

  - job_name: 'zookeeper'
    dns_sd_configs:
    - names:
      - 'tasks.zk-1'
      - 'tasks.zk-2'
      - 'tasks.zk-3'
      type: 'A'
      port: 9998

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'pushgateway'
    dns_sd_configs:
    - names:
      - 'tasks.pushgateway'
      type: 'A'
      port: 9091
