global:
  scrape_interval: 30s
  scrape_timeout: 20s
  evaluation_interval: 1m

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
