version: '3.5'

services:
  prometheus:
    deploy:
      placement:
        constraints:
          - node.role == worker

volumes:
  prometheus:
    name: prometheus-vol
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 5
      ebstype: gp2
