version: '3.5'

services:
  prometheus:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=${STORAGE_TSDB_RETENTION}'
    user: '0:0'
    networks:
      - metric-net
      - traefik-net
    environment:
      - JOBS
    volumes:
      - prometheus:/prometheus
    configs:
      - source: node_rules
        target: /etc/prometheus/swarm_node.rules.yml
      - source: task_rules
        target: /etc/prometheus/swarm_task.rules.yml
      - source: job_rules
        target: /etc/prometheus/swarm_job.rules.yml
      - source: service_rules
        target: /etc/prometheus/swarm_service.rules.yml
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.frontend.auth.basic.users: ${UI_AUTH}
        traefik.frontend.rule: Host:prometheus.${PUBLIC_HOSTNAME}
        traefik.backend: prometheus
        traefik.port: '9090'
      restart_policy:
        delay: 30s
        window: 2m
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          memory: 128M

networks:
  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: overlay
    attachable: ${METRIC_NET_ATTACHABLE:-true}

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

configs:
  node_rules:
    name: ${NODE_RULES_NAME:-node_rules}
    file: ./rules/swarm_node.rules.yml

  task_rules:
    name: ${TASK_RULES_NAME:-task_rules}
    file: ./rules/swarm_task.rules.yml

  job_rules:
    name: ${JOB_RULES_NAME:-job_rules}
    file: ./rules/swarm_job.rules.yml

  service_rules:
    name: ${SERVICE_RULES_NAME:-service_rules}
    file: ./rules/swarm_service.rules.yml