version: '3.5'

services:
  prometheus:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 256M

volumes:
  prometheus:
    name: ${PROMETHEUS_VOL_NAME:-prometheus-vol}

configs:
  node_rules:
    name: ${NODE_RULES_NAME:-node_rules}
    file: ./rules/swarm_node.rules.dev.yml
