version: '3.5'

services:
  prometheus:
    deploy:
      placement:
        constraints:
          - node.role == worker

volumes:
  prometheus:
    name: ${PROMETHEUS_VOL_NAME:-prometheus-vol}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: relocatable
      size: ${PROMETHEUS_VOL_SIZE:-10}
      ebstype: ${PROMETHEUS_VOL_EBS_TYPE:-gp2}
