groups:
- name: scheduled_job
  rules:
  - alert: backup_db_not_created
    expr: time() - backup_created_date_seconds{} > 86400
    labels:
      severity: warning
    annotations:
      description: Error creating backup for '{{ $labels.label }}' database.
      summary: Error creating backup for '{{ $labels.label }}' database.

  - alert: certificate_renew_not_attempted
    expr: time() - certificates_valid_date_seconds{} > 604800
    labels:
      severity: warning
    annotations:
      description: Error attemping to renew '{{ $labels.label }}' certificate.
      summary: Error attemping to renew '{{ $labels.label }}' certificate.

  - alert: certificate_not_renewed
    expr: time() - certificates_updated_date_seconds{} > 5788800
    labels:
      severity: warning
    annotations:
      description: Error, '{{ $labels.label }}' certificate near expiry.
      summary: Error, '{{ $labels.label }}' certificate near expiry.

  - alert: ElasticsearchSnapshotNotPerformed
    expr: time() - elasticsearch_snapshot_stats_snapshot_end_time_timestamp{} > 86400
    labels:
      severity: warning
    annotations:
      description: Last snapshot for '{{ $labels.repository }}' repository is too old.
      summary: Scheduled Elasticsearch snapshot is not working.

  - alert: ElasticsearchSnapshotCleanupNotPerformed
    expr: elasticsearch_snapshot_stats_number_of_snapshots{} > 64
    labels:
      severity: warning
    annotations:
      description: Too many snapshots ({{$value}}) found for '{{ $labels.repository }}' repository.
      summary: Scheduled Elasticsearch snapshot cleanup is not working.
