groups:
- name: swarm_task
  rules:
  - alert: task_high_cpu_usage_80
    expr: sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_task_name=~".+"}[1m]))
      BY (container_label_com_docker_swarm_task_name, container_label_com_docker_swarm_node_id)
      * 100 > 80
    for: 5m
    annotations:
      description: '{{ $labels.container_label_com_docker_swarm_task_name }} on ''{{
        $labels.container_label_com_docker_swarm_node_id }}'' CPU usage is at {{ humanize
        $value}}%.'
      summary: CPU alert for Swarm task '{{ $labels.container_label_com_docker_swarm_task_name }}'
        on '{{ $labels.container_label_com_docker_swarm_node_id }}'

  - alert: task_high_memory_usage_90
    expr: (sum(container_memory_rss{container_label_com_docker_swarm_task_name=~".+"})
      BY (container_label_com_docker_swarm_task_name, container_label_com_docker_swarm_node_id) /
      sum(container_spec_memory_limit_bytes{container_label_com_docker_swarm_task_name=~".+"})
      BY (container_label_com_docker_swarm_task_name, container_label_com_docker_swarm_node_id)) > 0.9
    for: 1m
    annotations:
      description: '{{ $labels.container_label_com_docker_swarm_task_name }} on ''{{
        $labels.container_label_com_docker_swarm_node_id }}'' memory usage is at {{ humanize
        $value}}%.'
      summary: Memory alert for Swarm task '{{ $labels.container_label_com_docker_swarm_task_name }}'
        on '{{ $labels.container_label_com_docker_swarm_node_id }}'
