global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 30s

  external_labels:
    monitor: 'promswarm'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
